version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: currency_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  rate-service:
    build:
      context: ./rate-service
    container_name: rate-service
    environment:
      - EXCHANGE_RATE_API_KEY=${EXCHANGE_RATE_API_KEY:-your-api-key}
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  main-service:
    build:
      context: ./main-service
    container_name: main-service
    environment:
      - RATE_SERVICE_URL=http://rate-service:8081
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rate-service:
        condition: service_started
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge